[package]
name = "path-jump"
version = "0.0.16"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"

[dependencies.rusqlite]
version = "0.25"
features = ["bundled"]

[[bin]]
name = "j"
path = "src/main.rs"
