[package]
name = "pj"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"

[dependencies.rusqlite]
version = "0.25"
features = ["bundled"]
