name: Release Build

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    name: Release Packaging
    env:
      PROJECT_BIN_NAME: j
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Test
        run: cargo test

      - name: Release Build
        run: cargo build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_BIN_NAME }}_${{ matrix.os }}
          path: |
            target/release/${{ env.PROJECT_BIN_NAME }}
            target/release/${{ env.PROJECT_BIN_NAME }}.sh
          if-no-files-found: error
