name: Tagged Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tagged_release:
    name: Tagged Release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    env:
      PROJECT_BIN_NAME: j
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Tag version
        id: tag_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Release Build
        run: cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          name: ${{ steps.tag_version.outputs.VERSION }}-${{ matrix.os }}
          tag_name: ${{ steps.tag_version.outputs.VERSION }}-${{ matrix.os }}
          files: |
            target/release/${{ env.PROJECT_BIN_NAME }}
            target/release/${{ env.PROJECT_BIN_NAME }}.sh
