name: Tagged Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tagged_release:
    name: Tagged Release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    env:
      PROJECT_BIN_NAME: j
      ARTIFACT_DIR: /home/runner/work/path-jump/path-jump/target/release
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Tag version
        id: tag_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Clippy check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Create artifact
        uses: TheDoctor0/zip-release@master
        with:
          type: zip
          filename: ${{ env.PROJECT_BIN_NAME }}_${{ matrix.os }}.zip
          directory: target/release/
          path: |
            ${{ env.PROJECT_BIN_NAME }}
            ${{ env.PROJECT_BIN_NAME }}.sh
      - name: Release artifact
        uses: softprops/action-gh-release@v1
        env:
          TAG_VERSION: ${{ steps.tag_version.outputs.VERSION }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG_VERSION }}
          prerelease: contains(github.ref, 'alpha') || contains(github.ref, 'beta')
          files: |
            target/release/${{ env.PROJECT_BIN_NAME }}_${{ matrix.os }}.zip
          fail_on_unmatched_files: true
