name: Tagged Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tagged_release:
    name: Tagged Release
    env:
      PROJECT_BIN_NAME: j
      ARTIFACT_DIR: /home/runner/work/path-jump/path-jump/target/release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Tag version
        id: tag_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set SDK for macOS aarch64
        if: ${{ matrix.target == 'aarch64-apple-darwin' && matrix.os == 'macos-latest' }}
        run: |
          sudo xcode-select -s "/Applications/Xcode_12.4.app"
          sudo rm -Rf /Library/Developer/CommandLineTools/SDKs/*

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Release build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      # - name: Setup tmate debug session
      #   if: ${{ failure() }}
      #   uses: mxschmitt/action-tmate@v3
      #   timeout-minutes: 30
      #   with:
      #     sudo: false
      #     limit-access-to-actor: true

      - name: Move final files
        run: |
          cp target/release/j.sh .
          cp target/${{ matrix.target }}/release/j .

      - name: Create zip artifact
        uses: TheDoctor0/zip-release@master
        with:
          type: zip
          filename: ${{ env.PROJECT_BIN_NAME }}_${{ matrix.target }}.zip
          path: |
            ${{ env.PROJECT_BIN_NAME }}
            ${{ env.PROJECT_BIN_NAME }}.sh

      - name: Create tar artifact
        uses: TheDoctor0/zip-release@master
        with:
          type: tar
          filename: ${{ env.PROJECT_BIN_NAME }}_${{ matrix.target }}.tar.gz
          path: |
            ${{ env.PROJECT_BIN_NAME }}
            ${{ env.PROJECT_BIN_NAME }}.sh

      - name: Cargo clean
        uses: actions-rs/cargo@v1
        with:
          command: clean

      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        env:
          TAG_VERSION: ${{ steps.tag_version.outputs.VERSION }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG_VERSION }}
          prerelease: contains(env.TAG_VERSION, 'alpha') || contains(env.TAG_VERSION, 'beta')
          files: |
            ${{ env.PROJECT_BIN_NAME }}_${{ matrix.target }}.zip
            ${{ env.PROJECT_BIN_NAME }}_${{ matrix.target }}.tar.gz
          fail_on_unmatched_files: true
