name: Tagged Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tagged_release:
    name: Tagged Release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    env:
      PROJECT_BIN_NAME: j
      GITHUB_REPOSITORY: 5c077m4n/path-jump
      TAG_VERSION: ${GITHUB_REF/refs\/tags\//}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Clippy check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Release Build
        run: cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: endsWith(github.ref, 'alpha') || endsWith(github.ref, 'beta')
          name: ${{ env.TAG_VERSION }}-${{ matrix.os }}
          tag_name: ${{ env.TAG_VERSION }}-${{ matrix.os }}
          files: |
            target/release/${{ env.PROJECT_BIN_NAME }}
            target/release/${{ env.PROJECT_BIN_NAME }}.sh
          fail_on_unmatched_files: true
